import { useProjectStore } from "@/stores/project-store";
import type { Project, Epic, Story, Task, Bug, TeamMember } from "@/types";

export function loadSeedData(): void {
  const TIMESTAMP = "2026-03-01T09:00:00.000Z";

  const team: TeamMember[] = [
    {
      id: "member-1",
      name: "Marco",
      color: "#2563EB",
      role: "Tech Lead",
      hoursPerDay: 8,
    },
    {
      id: "member-2",
      name: "Sara",
      color: "#7C3AED",
      role: "AI Engineer",
      hoursPerDay: 8,
    },
    {
      id: "member-3",
      name: "Luca",
      color: "#059669",
      role: "Full Stack Dev",
      hoursPerDay: 8,
    },
  ];

  const epic1: Epic = {
    id: "epic-1",
    type: "epic",
    title: "Data Pipeline",
    description: "",
    status: "in_progress",
    priority: "high",
    assigneeId: null,
    estimatedDays: 0,
    dependencies: [],
    tags: [],
    parentId: null,
    order: 0,
    targetDate: "2026-06-30",
    createdAt: TIMESTAMP,
    updatedAt: TIMESTAMP,
  };

  const epic2: Epic = {
    id: "epic-2",
    type: "epic",
    title: "Model Training",
    description: "",
    status: "in_progress",
    priority: "critical",
    assigneeId: null,
    estimatedDays: 0,
    dependencies: [],
    tags: [],
    parentId: null,
    order: 1,
    targetDate: "2026-07-31",
    createdAt: TIMESTAMP,
    updatedAt: TIMESTAMP,
  };

  const story1: Story = {
    id: "story-1",
    type: "story",
    title: "Implement data ingestion API",
    description: "",
    status: "in_progress",
    priority: "high",
    assigneeId: "member-3",
    estimatedDays: 0,
    dependencies: [],
    tags: [],
    parentId: "epic-1",
    order: 0,
    storyPoints: 5,
    acceptanceCriteria: "",
    createdAt: TIMESTAMP,
    updatedAt: TIMESTAMP,
  };

  const story2: Story = {
    id: "story-2",
    type: "story",
    title: "Build data validation layer",
    description: "",
    status: "todo",
    priority: "medium",
    assigneeId: "member-2",
    estimatedDays: 0,
    dependencies: [],
    tags: [],
    parentId: "epic-1",
    order: 1,
    storyPoints: 3,
    acceptanceCriteria: "",
    createdAt: TIMESTAMP,
    updatedAt: TIMESTAMP,
  };

  const story3: Story = {
    id: "story-3",
    type: "story",
    title: "Design model architecture",
    description: "",
    status: "in_review",
    priority: "critical",
    assigneeId: "member-2",
    estimatedDays: 0,
    dependencies: [],
    tags: [],
    parentId: "epic-2",
    order: 0,
    storyPoints: 8,
    acceptanceCriteria: "",
    createdAt: TIMESTAMP,
    updatedAt: TIMESTAMP,
  };

  const story4: Story = {
    id: "story-4",
    type: "story",
    title: "Build training pipeline",
    description: "",
    status: "todo",
    priority: "high",
    assigneeId: "member-1",
    estimatedDays: 0,
    dependencies: [],
    tags: [],
    parentId: "epic-2",
    order: 1,
    storyPoints: 5,
    acceptanceCriteria: "",
    createdAt: TIMESTAMP,
    updatedAt: TIMESTAMP,
  };

  const task1: Task = {
    id: "task-1",
    type: "task",
    title: "Set up FastAPI endpoints",
    description: "",
    status: "done",
    priority: "medium",
    assigneeId: "member-3",
    estimatedDays: 2,
    dependencies: [],
    tags: [],
    parentId: "story-1",
    order: 0,
    createdAt: TIMESTAMP,
    updatedAt: TIMESTAMP,
  };

  const task2: Task = {
    id: "task-2",
    type: "task",
    title: "Implement S3 connector",
    description: "",
    status: "in_progress",
    priority: "medium",
    assigneeId: "member-3",
    estimatedDays: 3,
    dependencies: [],
    tags: [],
    parentId: "story-1",
    order: 1,
    createdAt: TIMESTAMP,
    updatedAt: TIMESTAMP,
  };

  const task3: Task = {
    id: "task-3",
    type: "task",
    title: "Define Zod schemas",
    description: "",
    status: "todo",
    priority: "medium",
    assigneeId: "member-2",
    estimatedDays: 1,
    dependencies: [],
    tags: [],
    parentId: "story-2",
    order: 0,
    createdAt: TIMESTAMP,
    updatedAt: TIMESTAMP,
  };

  const task4: Task = {
    id: "task-4",
    type: "task",
    title: "Write validation middleware",
    description: "",
    status: "todo",
    priority: "medium",
    assigneeId: "member-2",
    estimatedDays: 2,
    dependencies: ["task-3"],
    tags: [],
    parentId: "story-2",
    order: 1,
    createdAt: TIMESTAMP,
    updatedAt: TIMESTAMP,
  };

  const task5: Task = {
    id: "task-5",
    type: "task",
    title: "Research transformer architectures",
    description: "",
    status: "done",
    priority: "medium",
    assigneeId: "member-2",
    estimatedDays: 2,
    dependencies: [],
    tags: [],
    parentId: "story-3",
    order: 0,
    createdAt: TIMESTAMP,
    updatedAt: TIMESTAMP,
  };

  const task6: Task = {
    id: "task-6",
    type: "task",
    title: "Document architecture decision",
    description: "",
    status: "in_review",
    priority: "medium",
    assigneeId: "member-2",
    estimatedDays: 1,
    dependencies: ["task-5"],
    tags: [],
    parentId: "story-3",
    order: 1,
    createdAt: TIMESTAMP,
    updatedAt: TIMESTAMP,
  };

  const task7: Task = {
    id: "task-7",
    type: "task",
    title: "Set up PyTorch training loop",
    description: "",
    status: "todo",
    priority: "medium",
    assigneeId: "member-1",
    estimatedDays: 3,
    dependencies: ["task-6"],
    tags: [],
    parentId: "story-4",
    order: 0,
    createdAt: TIMESTAMP,
    updatedAt: TIMESTAMP,
  };

  const task8: Task = {
    id: "task-8",
    type: "task",
    title: "Implement data loaders",
    description: "",
    status: "todo",
    priority: "medium",
    assigneeId: "member-3",
    estimatedDays: 2,
    dependencies: ["task-7"],
    tags: [],
    parentId: "story-4",
    order: 1,
    createdAt: TIMESTAMP,
    updatedAt: TIMESTAMP,
  };

  const bug1: Bug = {
    id: "bug-1",
    type: "bug",
    title: "S3 timeout on large files",
    description: "",
    status: "todo",
    priority: "high",
    assigneeId: "member-3",
    estimatedDays: 1,
    dependencies: [],
    tags: [],
    parentId: "story-1",
    order: 2,
    severity: "high",
    stepsToReproduce: "",
    createdAt: TIMESTAMP,
    updatedAt: TIMESTAMP,
  };

  const bug2: Bug = {
    id: "bug-2",
    type: "bug",
    title: "Memory leak in tokenizer",
    description: "",
    status: "in_progress",
    priority: "critical",
    assigneeId: "member-2",
    estimatedDays: 2,
    dependencies: [],
    tags: [],
    parentId: "story-3",
    order: 2,
    severity: "critical",
    stepsToReproduce: "",
    createdAt: TIMESTAMP,
    updatedAt: TIMESTAMP,
  };

  const project: Project = {
    id: "seed-project-1",
    name: "ICCREA AI Platform",
    deadline: null,
    team,
    items: [
      epic1,
      epic2,
      story1,
      story2,
      story3,
      story4,
      task1,
      task2,
      task3,
      task4,
      task5,
      task6,
      task7,
      task8,
      bug1,
      bug2,
    ],
    overrides: [],
    createdAt: TIMESTAMP,
    updatedAt: TIMESTAMP,
  };

  useProjectStore.getState().importProject(project);
}
